[package]
name = "qendil-core"
version = "0.0.1"
authors = ["Said Dermoumi <hi@sdrm.me>"]
edition = "2018"
description = "Core shared functionality of the Qendil server"
repository = "https://github.com/qendil/qendil/"
license-file = "../../LICENSE"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "~0.2.81"
console_error_panic_hook = { version = "~0.1.6", optional = true }
wee_alloc = { version = "~0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "~0.3.31"
