name: Build Linux binaries

on:
  push:
    tags:
      - client/*

permissions:
  contents: write

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: "latest"

      - name: Setup Node with caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: >-
          pnpm install --frozen-lockfile --strict-peer-dependencies --production

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - name: Build the clients
        run: pnpm build:linux
        env:
          CLIENT_PLATFORM: cdv-linux
          CLIENT_SENTRY_ENVIRONMENT: production
          CLIENT_SENTRY_DSN: "${{ secrets.CLIENT_SENTRY_DSN }}"

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: packages/client/dist/*
          generate_release_notes: false
          append_body: true
          draft: true
