name: Build Android app

on:
  push:
    tags:
      - client/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: "latest"

      - name: Setup Node with caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: >-
          pnpm install --frozen-lockfile --strict-peer-dependencies --production

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.8

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - name: Build the clients
        run: |
          echo "${{ secrets.ANDROID_KEY }}" | base64 --decode \
            > packages/client/release.key
          pnpm build:android -- -- \
            --packageType=apk \
            --keystore=release.key \
            --storePassword="${{ secrets.ANDROID_KEY_STORE_PASSWORD }}" \
            --password="${{ secrets.ANDROID_KEY_PASSWORD }}" \
            --alias=qendil-release
        env:
          CLIENT_PLATFORM: cdv-android
          CLIENT_SENTRY_ENVIRONMENT: production
          CLIENT_SENTRY_DSN: "${{ secrets.CLIENT_SENTRY_DSN }}"

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: packages/client/dist/*
          generate_release_notes: false
          append_body: true
          draft: true
