name: Deploy Staging

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-types:
    name: Typecheck files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: "latest"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Setup Node with caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Lint the code
        run: pnpm lint:types

  check-formatting:
    name: Check files formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: "latest"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Setup Node with caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Lint the code
        run: pnpm lint:format

  check-linting:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: "latest"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Setup Node with caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Lint the code
        run: pnpm lint:practices

  deploy_to_staging:
    name: Deploy to staging
    needs:
      - check-types
      - check-formatting
      - check-linting
    environment:
      name: Staging
      url: ${{ steps.publish-client.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: "latest"

      - name: Setup Node with caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --strict-peer-dependencies --production

      - name: Build the client
        working-directory: client/
        run: pnpm build

      - name: Publish client to cloudflare
        id: publish-client
        working-directory: client/
        run: |
          if [[ "${{ github.ref }}" =~ refs/pull/.+ ]]; then
            # Pull requests deploy to their own staging environments
            : "${{ github.ref }}"
            : ${_%%\/merge}  # Remove 'merge' at the end
            : ${_//refs\/pull\/}  # Remove 'refs' at the beginning
            TARGET="pull request ${_}"
          else
            TARGET="${{ github.ref_name }}"
          fi

          # Use wrangler to manually deploy to cloudflare
          pnpm dlx wrangler pages publish www/ --project-name=qendil-staging \
            --branch="$TARGET" --commit-dirty=true | tee wrangler.out

          # Parse the output URL from the wrangler output
          TARGET_URL=$(grep -oE "https?://.+" wrangler.out | tail -n1)
          if [[ "$TARGET_URL" ]]; then
            echo "::set-output name=url::$TARGET_URL"
          else
            echo "Failed to find URL for deployment"
            exit 1
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
